### ISSUE TITLE
is this library still maintained? would like to request for typing

### ISSUE THREAD

**Issue by tylim88** [arthurvr/split-array#2]

**Comment by tylim88** [comment]
ah nevermind, judging that this repo last commit is 5 years ago, I doubt there will be any update

so I copied the code and add typescript support myself

https://www.npmjs.com/package/array-chop

credited original author

**Comment by christopher-caldwell** [comment]
Came across this issue as I wanted to do the same thing. Thanks for your effort with the types! Using your lib instead @tylim88
